---
- name: Install inetutils for hostname
  when: ansible_distribution == 'Archlinux'
  pacman:
      name: inetutils
      state: present

- name: Set the hostname
  when: ansible_distribution == 'Archlinux'
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"