---
- hosts: localhost
  roles:
    - { role: aur, tags: ['aur'] }
    - { role: 1pass, tags: ['1pass'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: vim, tags: ['vim'] }
    - { role: zprezto, tags: ['zprezto'] }
    - { role: x, tags: ['x'] }
    - { role: i3, tags: ['i3'] }
    - { role: wallpapers, tags: ['wallpapers'] }
    - { role: polybar, tags: ['polybar'] }
    - { role: rofi, tags: ['rofi'] }
    - { role: docker, tags: ['docker'] }

- hosts: localhost
  tasks:
    - name: Include role to iterate over release channels
      include_role:
        name: discord
      tags:
        - discord
      with_items:
        - release_channel: stable
          binary_name: Discord
        - release_channel: ptb
          binary_name: DiscordPTB
        - release_channel: canary
          binary_name: DiscordCanary
