---
- hosts: arch-laptop
  roles:
    - { role: aur, tags: ['aur'] }
    - { role: 1pass, tags: ['1pass'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: vim, tags: ['vim'] }
    - { role: zprezto, tags: ['zprezto'] }
    - { role: sway, tags: ['sway'] }
    - { role: waybar, tags: ['waybar'] }
    - { role: docker, tags: ['docker'] }
    - { role: audio, tags: ['audio'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: notifs, tags: ['notifs'] }

- hosts: arch-laptop
  tasks:
    - name: Include role to iterate over release channels
      include_role:
        name: discord
      tags:
        - discord
      with_items:
        - release_channel: stable
          binary_name: Discord
        - release_channel: ptb
          binary_name: DiscordPTB
        - release_channel: canary
          binary_name: DiscordCanary

- hosts: mac-laptop
  roles:
  - { role: repo, tags: ['repo'] }
  - { role: dotfiles, tags: ['dotfiles'] }

- hosts: k8s
  roles: 
  #- { role: repo, tags: ['repo'] }
  #- { role: vim, tags: ['vim']}
  #- { role: aur, tags: ['aur']}
  #- { role: docker, tags: ['docker'] }
  - { role: oh-my-zsh, tags: ['oh-my-zsh'] }
  - { role: dotfiles, tags: ['dotfiles'] }
  #- { role: debug, tags: ['debug'] }