---
- hosts: localhost
  roles:
    - { role: aur, tags: ['aur'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: zprezto, tags: ['zprezto'] }
    - { role: x, tags: ['x'] }
    - { role: i3, tags: ['i3'] }
    - { role: wallpapers, tags: ['wallpapers'] }
    - { role: polybar, tags: ['polybar'] }
    - { role: 1pass, tags: ['1pass'] }


#- hosts: all
#  tasks:
#  - name: Install common apt packages
#    apt: name={{item}}
#    become: yes
#    become_user: root
#    with_items:
#      - htop
#      - software-properties-common
#      - unzip
#      - curl
#      - network-manager
#      - xinit
#      - tilda
#      - xclip
#      - rofi
#      - slim
#      - xbacklight
#      - font-manager
#      - tree
#      - curl
#      - zsh
#      - redshift
#      - fonts-powerline
#
#
#- hosts: all
#  tasks:
#  - apt_repository:
#      repo: ppa:kgilmer/speed-ricer
#
#  - name: Install i3-gaps & polybar
#    apt: name={{item}}
#    become: yes
#    become_user: root
#    with_items:
#      - i3-gaps
#      - polybar
#
#- hosts: all
#  name: Install 1pass cmd line
#  vars:
#  - version: v0.10.0
#  tasks:
#  - name: Check if op exists
#    stat:
#      path: /usr/local/bin/op
#    register: op
#
#  - name: Download zip
#    when: op.stat.exists == False
#    get_url:
#      url: "https://cache.agilebits.com/dist/1P/op/pkg/{{ version }}/op_linux_amd64_v0.10.0.zip"
#      dest: "/tmp/op_linux_amd64_{{ version }}.zip"
#
#  - name: Unarchive zip
#    when: op.stat.exists == False
#    unarchive:
#      src: "/tmp/op_linux_amd64_{{ version }}.zip"
#      dest: /tmp
#
#  - name: Moves op to /usr/local/bin
#    when: op.stat.exists == False
#    file:
#      owner: "{{user}}"
#      group: "{{user}}"
#      src: /tmp/op
#      dest: /usr/local/bin/op
#      state: hard
#
#- hosts: all
#  name: Fetch ssh keys
#  vars:
#  tasks:
#  - command:
#      cmd: 'op get document id_rsa'
#    environment:
#      OP_SESSION_my: "{{ lookup('env','OP_SESSION_my') }}"
#    register: id_rsa
#    tags: secrets
#
#
#  - name: Fetch ssh key
#    tags: secrets
#    copy:
#      dest: "{{ home_dir }}/.ssh/id_rsa"
#      content: "{{ id_rsa.stdout }}"
#      mode: '0600'
#
#  - command:
#      cmd: 'op get document id_rsa.pub'
#    environment:
#      OP_SESSION_my: "{{ lookup('env','OP_SESSION_my') }}"
#    register: id_rsa_pub
#    tags: secrets
#
#
#  - name: Fetch ssh key
#    tags: secrets
#    copy:
#      dest: "{{ home_dir }}/.ssh/id_rsa.pub"
#      content: "{{ id_rsa_pub.stdout }}"
#
#
#- hosts: all
#  name: VSCode
#  vars:
#    vscode_dir: '/opt/vscode'
#  tasks:
#  - name: Check if vscode is installed
#    tags: vscode
#    stat:
#      path: '/usr/local/bin/code'
#    register: vscode
#
#  - name: Make vscode dir
#    when: vscode.stat.exists == False
#    tags: vscode
#    become: yes
#    become_user: root
#    file:
#      owner: "{{user}}"
#      group: "{{user}}"
#      path: '{{ vscode_dir }}'
#      state: directory
#
#  - name: Download vscode
#    when: vscode.stat.exists == False
#    tags: vscode
#    get_url:
#      url: 'https://go.microsoft.com/fwlink/?LinkID=620884'
#      dest: '/tmp/vscode.tar.gz'
#
#  - name: Unarchive vscode
#    when: vscode.stat.exists == False
#    tags: vscode
#    unarchive:
#      owner: '{{user}}'
#      src: '/tmp/vscode.tar.gz'
#      dest: '{{ vscode_dir }}'
#      extra_opts: [--strip-components=1]
#
#  - name: Unarchive vscode
#    when: vscode.stat.exists == False
#    become: yes
#    become_user: root
#    tags: vscode
#    file:
#      src: '/opt/vscode/bin/code'
#      dest: '/usr/local/bin/code'
#      state: link
#      force: yes
#
#