---
- hosts: localhost
  roles:
    - { role: aur, tags: ['aur'] }
    - { role: 1pass, tags: ['1pass'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: vim, tags: ['vim'] }
    - { role: zprezto, tags: ['zprezto'] }
    - { role: sway, tags: ['sway'] }
    - { role: docker, tags: ['docker'] }
    - { role: audio, tags: ['audio'] }

- hosts: localhost
  tasks:
    - name: Include role to iterate over release channels
      include_role:
        name: discord
      tags:
        - discord
      with_items:
        - release_channel: stable
          binary_name: Discord
        - release_channel: ptb
          binary_name: DiscordPTB
        - release_channel: canary
          binary_name: DiscordCanary
