---
- name: Check if zprezto was cloned
  stat:
    path: '/home/{{ user.name }}/.zprezto'
  register: zprezto
  tags:
    - zprezto

- name: Clone zprezto
  tags: zsh
  when: zprezto.stat.exists == False
  git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: '/home/{{ user.name }}/github.com/sorin-ionescu/prezto'
    update: yes
    recursive: True
  tags:
    - zprezto

- name: Symlink to home
  tags: zsh
  when: zprezto.stat.exists == False
  file:
    src: '/home/{{ user.name }}/github.com/sorin-ionescu/prezto'
    dest: zprezto.stat.path
    state: link
    force: yes
  tags:
    - zprezto
