---
- name: Check if zprezto was cloned
  stat:
    path: '/home/{{ user.name }}/.zprezto'
  register: zprezto
  tags:
    - zprezto

- name: Clone zprezto
  tags: zsh
  when: zprezto.stat.exists == False
  git:
    repo: 'https://github.com/sorin-ionescu/prezto.git'
    dest: '/home/{{ user.name }}/.zprezto'
    update: yes
    recursive: True
  tags:
    - zprezto
