---
- name: Print some debug information
  debug:
    msg: "{{ repo_path }}/dotfiles"
  tags: dotfiles

- name: Find dotfiles in repo_dir
  find:
    paths: "{{ repo_path }}/dotfiles"
    hidden: 'yes'
    file_type: 'file'
  register: dots

- user:
    name: "{{ user.name }}"
  register: user_var

- name: Print some debug information
  with_items: '{{ dots.files }}'
  debug:
    msg: "{{ item }}"
  tags: dotfiles

- name: Symlinks all dotfiles
  file:
    src: "{{ item.path }}"
    dest: "{{ user_var.home }}/{{item.path | basename }}"
    state: link
    force: yes
    mode: "{{ item.mode }}"
  with_items: "{{ dots.files }}"
  tags:
    - dotfiles
