---
- name: Symlinks all dotfiles
  file:
    src: "{{item.src}}"
    dest: "/home/{{ user.name }}/{{item.path}}"
    state: link
    force: yes
    mode: "{{item.mode}}"
  with_filetree: '{{ repo_path }}/dotfiles/files'
  when: item.state == 'file'
  tags:
    - dotfiles