## {{ ansible_managed }}

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: alacritty

window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

background_opacity: .95

selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true


working_directory: {{ user_var.home }}

font:
  normal:
    family: SF Mono Powerline
  size: 12.0

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'
