---
- name: Install i3-gap
  aur: name=i3-gaps-next-git
  become: yes
  become_method: su
  become_user: "{{ user.name }}"
  tags:
    - i3

- name: Copy i3 config
  template:
    src: config.j2
    dest: /home/{{ user.name }}/.config/i3/config
  tags:
    - i3