---
- name: Install i3-gap
  aur: name=i3-gaps-next-git
  tags:
    - i3

- name: Make i3 config dir
  file: path=/home/{{ user.name }}/.config/i3 state=directory

- name: Copy i3 config
  template:
    src: config.j2
    dest: /home/{{ user.name }}/.config/i3/config
    force: true
  tags:
    - i3