---
- name: Install i3-gap
  aur: name=i3-gaps-next-git
  tags:
    - i3

- name: Install screen lock deps
  pacman:
    state: present
    name: 
      - i3lock 
      - scrot
      - imagemagick

- name: Move lock script
  become: yes
  file: 
    src: '{{ repo_path }}/roles/i3/files/lock.sh'
    dest: /bin/lock
    force: true
    state: link

- name: Make i3 config dir
  file: path=/home/{{ user.name }}/.config/i3 state=directory

- name: Symlink config file
  file:
    src: '{{ repo_path }}/roles/i3/files/config'
    dest: '/home/{{ user.name }}/.config/i3/config'
    state: link
    force: true
  tags:
    - i3

- name:
  pacman: name=feh state=present
  become: yes

- name: Symlinks wallpaper dir
  file:
    src: "{{ repo_path }}/roles/i3/wallpapers"
    dest: "/home/{{ user.name }}/wallpapers"
    state: link
    force: yes
  tags:
    - wallpapers
