---
- name: Install rofi
  pacman: name=rofi state=present
  become: yes
  tags:
    - rofi

- name: Make sure config folder exists
  file: path=/home/{{ user.name }}/.config/rofi state=directory

- name: Link rofi config
  file:
    src: "{{item.src}}"
    dest: "/home/{{ user.name }}/.config/rofi/{{ item.path }}"
    force: true
    state: link
    mode: "{{item.mode}}"
  with_filetree: './roles/rofi/config'
  when: item.state == 'file'
  tags:
    - rofi

- name: Make sure config folder exists
  file: path=/home/{{ user.name }}/.local/share/rofi/themes state=directory

- name: Link rofi themes
  file:
    src: "{{item.src}}"
    dest: "/home/{{ user.name }}/.local/share/rofi/themes/{{ item.path }}"
    force: true
    state: link
    mode: "{{item.mode}}"
  with_filetree: './roles/rofi/themes'
  when: item.state == 'file'
  tags:
    - rofi
