---
- name: Install sudo
  when: ansible_distribution == 'Archlinux'
  become: yes
  pacman:
    name: sudo
    state: present
  tags:
    - sudo

- name: Copy sudo configuration
  when: ansible_distribution == 'Archlinux'
  become: yes
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 440
    validate: 'visudo -cf %s'
  tags:
    - sudo
