---
- name: Check if dev was cloned
  stat:
    path: '{{ repo_path }}'
  register: repo
  tags:
    - repo

- name: Make repo
  file: path={{ repo_path }} state=directory
  when: repo.stat.exists == False

- name: Clone repo
  when: repo.stat.exists == False
  git:
    repo: 'https://github.com/enkoder/dev.git'
    dest: '{{ repo_path }}'
    recursive: True
    update: yes
  tags:
    - repo

- name: Clone repo
  when: repo.stat.exists == False
  file:
    path: '{{ repo_path }}'
    recurse: True
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags:
    - repo
