---
- name: Check if dev was cloned
  stat:
    path: '{{ repo }}'
  register: repo
  tags:
    - repo

- name: Make repo
  file: path={{ repo | dirname }} state=directory

- name: Clone repo
  when: repo.stat.exists == False
  git:
    repo: 'https://github.com/enkoder/dev.git'
    dest: '{{ repo }}'
    recursive: True
    update: yes
  tags:
    - repo
