---
- name: Install pip
  pacman: name=python-pip state=present
  tags:
    - repo

- name: Install linter
  pip:
    name:
      - ansible-lint
      - pre-commit
  tags:
    - repo

- name: Check if dev was cloned
  stat:
    path: '{{ repo_path }}'
  register: repo
  tags:
    - repo

- name: Make repo
  file: path={{ repo_path | dirname }} state=directory

- name: Clone repo
  when: repo.stat.exists == False
  git:
    repo: 'https://github.com/enkoder/dev.git'
    dest: '{{ repo_path }}'
    recursive: True
    update: yes
  tags:
    - repo

- name: Clone repo
  when: repo.stat.exists == False
  file:
    path: '{{ repo_path }}'
    recurse: True
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags:
    - repo
