---
- name: Check if dev was cloned
  stat:
    path: /home/{{ user.name }}/github.com/enkoder/dev
  register: repo
  tags:
    - repo

- name: Make repo
  file: path=/home/{{ user.name }}/github.com/enkoder state=directory
  become: yes
  become_method: su
  become_user: "{{ user.name }}"

- name: Clone repo
  when: repo.stat.exists == False
  git:
    repo: 'https://github.com/enkoder/dev.git'
    dest: '/home/{{ user.name }}/github.com/enkoder/dev'
    recursive: True
  become: yes
  become_method: su
  become_user: "{{ user.name }}"
  tags:
    - repo
