---
- name: Create alacritty dir
  file: path=/home/{{ user.name }}/.config/alacritty state=directory
  tags:
    - terminal

- name: Symlink config file
  file:
    src: '{{ repo_path }}/roles/terminal/files/alacritty.yml'
    dest: '/home/{{ user.name }}/.config/alacritty/alacritty.yml'
    state: link
    force: true
  tags:
    - terminal
