---
- name: Install sway
  aur:
    name:
      - swaynagmode
      - bemenu-wlroots
  tags:
    - sway

- name: Install screen lock deps
  become: yes
  pacman:
    state: present
    name:
      - sway
      - wlroots
      - grim
      - slurp
      - imagemagick
  tags:
    - sway

- name: Move lock script
  become: yes
  file:
    src: '{{ repo_path }}/roles/sway/files/lock'
    dest: /bin/lock
    force: true
    state: link

- name: Make sway config dir
  file: path=/home/{{ user.name }}/.config/sway state=directory

- name: Symlink config file
  file:
    src: '{{ repo_path }}/roles/sway/files/config'
    dest: '/home/{{ user.name }}/.config/sway/config'
    state: link
    force: true
  tags:
    - sway

- name: Symlinks wallpaper dir
  file:
    src: "{{ repo_path }}/roles/sway/wallpapers"
    dest: "/home/{{ user.name }}/wallpapers"
    state: link
    force: yes
  tags:
    - sway
