---
- user:
    name: aur_builder
    group: wheel

- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Create AUR directory
  file: path=/home/{{ user.name }}/{{ aur.dir }}
        state=directory
        owner={{ user.name }}
        group={{ user.group }}
  tags:
    - aur

- name: Check if yay was cloned
  stat:
    path: /root/github.com/yay
  register: yay_git
  tags:
    - aur

- name: Check is yay installed
  shell: command -v yay >/dev/null 2>&1
  register: yay
  ignore_errors: yes
  tags:
    - aur

- name: Clone yay
  when: yay_git.stat.exists == False
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: /root/github.com/yay
  become: yes
  become_user: aur_builder
  tags:
    - aur

- name: Install yay
  when: yay.rc != 0
  shell:
    cmd: makepkg -i
    chdir: /root/github.com/yay
  become: yes
  become_user: aur_builder
  tags:
    - aur

- name: Install AUR base packages
  aur:
    name: "{{ aur.packages }}"
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - aur