---
- name: Create AUR directory
  file: path=/home/{{ user.name }}/{{ aur.dir }}
        state=directory
        owner={{ user.name }}
        group={{ user.group }}
  tags:
    - aur

- name: Check if yay was cloned
  stat:
    path: /home/{{ user.name }}/github.com/yay
  register: yay_git
  tags:
    - aur

- name: Check is yay installed
  shell: command -v yay >/dev/null 2>&1
  register: yay
  ignore_errors: yes
  tags:
    - aur

- name: Clone yay
  when: yay_git.stat.exists == False
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: /home/{{ user.name }}/github.com/yay
  tags:
    - aur

- name: Change owner to aur_builder
  file:
    path: /home/{{ user.name }}/github.com/yay
    state: directory
    recurse: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Install aur
  pacman: name=go state=present
  tags:
    - aur

- name: Install yay
  when: yay.rc != 0
  shell:
    cmd: makepkg -i -f --noconfirm
    chdir: /home/{{ user.name }}/github.com/yay
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install AUR base packages
  aur:
    name: "{{ aur.packages }}"
    use: yay
    state: present
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur