---
- name: Install inetutils for hostname
  pacman:
      name: inetutils
      state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- include: shell.yml
- include: user.yml
- include: sudo.yml
- include: packages.yml
