---
- name: Check if vimplug is installed
  stat:
    path: /home/{{ user.name }}/.vim/autoload/plug.vim
  register: plug
  tags:
    - vim

- name: Create autoplug dir
  file: path=/home/{{ user.name }}/.vim/autoload state=directory
  tags:
    - vim

- name: Fetch vimplug
  when: plug.stat.exists == False
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ user.name }}/.vim/autoload/plug.vim"
  tags:
    - vim
