---
- name: Install vim & neovim
  become: yes
  pacman:
    state: present
    name:
      - vim
      - neovim
  tags:
    - vim

- name: Check if vimplug is installed
  stat:
    path: /home/{{ user.name }}/.vim/autoload/plug.vim
  register: plug
  tags:
    - vim

- name: Create autoplug dir
  file: path=/home/{{ user.name }}/.vim/autoload state=directory
  tags:
    - vim

- name: Fetch vimplug
  when: plug.stat.exists == False
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ user.name }}/.vim/autoload/plug.vim"
  tags:
    - vim

- name: Create nvim dir
  file: path=/home/{{ user.name }}/.config/nvim state=directory
  tags:
    - vim

- name: Symlink vimrc file
  file:
    src: '{{ repo_path }}/roles/vim/files/vimrc'
    dest: '/home/{{ user.name }}/.vimrc'
    state: link
    force: true
  tags:
    - vim

- name: Symlink init.vim file
  file:
    src: '{{ repo_path }}/roles/vim/files/init.vim'
    dest: '/home/{{ user.name }}/.config/nvim/init.vim'
    state: link
    force: true
  tags:
    - vim
